### ISSUE TITLE
when layer deepth more than 7

### ISSUE THREAD

**Issue by zoucdr** [NtreevSoft/psd-parser#3]
hi, i`am using your psd parser.
thank your project so mach .that we can generate sprite from psd very quickly now.
but when our psd deepth more than 7,can not analysis correct any more.
will you update it? for i can not understand all of your design method currently.

**Comment by s2quake** [comment]
thank you for using psd library
If you send me a simple test file, it will help me solve it.
s2quake@ntreev.com

**Comment by s2quake** [comment]
The problem is not the depth, but the properties that are not described in the document. The problem was corrected.
