### ISSUE TITLE
fontName is empty

### ISSUE THREAD

**Issue by Ribosome2** [NtreevSoft/psd-parser#8]
great parser !
fontName in TextInfo : styleSheetsData["Font"]  is always empty , is this an unplemented feature or PS version issue ?

**Comment by Ribosome2** [comment]
Font value is always 0 not emty,  how do I get the fontName of textInfo

**Comment by Ribosome2** [comment]
I found that I can get fontName in engineData["ResourceDict"] ,打扰了

**Comment by s2quake** [comment]
I'm glad the problem was solved.
